"""GENERATED by semantic/reflect.py -- DO NOT EDIT.

Physical layer reflected from the Schema Registry; semantics merged
from overlay YAML. Edit the overlay, then regenerate.
"""

from sqlalchemy import (
    BigInteger, Boolean, Column, Date, DateTime, Float, Integer,
    LargeBinary, Numeric, String, Time,
)
from sqlalchemy.orm import DeclarativeBase

from semantido import SemanticBase, semantic_table


class TopicBase(SemanticBase, DeclarativeBase):
    """Declarative base used only for semantic extraction."""


@semantic_table(
    description='EMIR trade reports (one record per submission, append-only). Dual-sided: each economic trade normally appears twice.',
    synonyms=['EMIR reports', 'transaction reports', 'TR submissions'],
    application_context='Count economic trades with COUNT(DISTINCT uti). counterparty_1/2 are LEIs of legal parties -- never join to clearing member codes.',
    time_dimension='reporting_timestamp',
)
class EmirTradeReports(TopicBase):
    __tablename__ = 'emir.trade-reports'

    report_id = Column(String, primary_key=True)
    uti = Column(String)
    uti_description = 'Unique Transaction Identifier'
    uti_application_rules = ['COUNT(DISTINCT uti) = economic trades; COUNT(*) counts submissions (approx. double).']
    counterparty_1 = Column(String)
    counterparty_1_description = 'LEI of the reporting counterparty (EMIR field 1.4)'
    counterparty_1_synonyms = ['reporting counterparty', 'CP1']
    counterparty_1_concept = 'counterparty.emir_reporting'
    counterparty_2 = Column(String)
    counterparty_2_description = 'LEI of the other counterparty (EMIR field 1.9)'
    counterparty_2_concept = 'counterparty.emir_reporting'
    action_type = Column(String)
    action_type_sample_values = ['NEWT', 'MODI', 'EROR', 'TERM']
    action_type_application_rules = ['Live trades = latest action per UTI not in (EROR, TERM).']
    notional = Column(Float, nullable=True)
    reporting_timestamp = Column(DateTime)


@semantic_table(
    description='COMPACTED state topic: current net position per key (clearing_member_id, account, contract_series). Each record is a full replacement snapshot for its key, not a delta.',
    synonyms=['positions', 'open interest by member'],
    application_context='Lenses SQL: query as `etd.positions`. COMPACTION SEMANTICS: take the latest record per key (max _meta.offset per partition/key) before any aggregation; aggregating over full history double-counts.',
    business_context='Netted post-clearing positions maintained by the CCP.',
    time_dimension='as_of_time',
    concept='position.net',
)
class EtdPositions(TopicBase):
    __tablename__ = 'etd.positions'

    position_key = Column(String, primary_key=True)
    clearing_member_id = Column(String)
    clearing_member_id_description = 'Clearing member holding the position'
    clearing_member_id_concept = 'counterparty.clearing_member'
    account = Column(String)
    account_sample_values = ['A1', 'P1']
    contract_series = Column(String)
    net_quantity = Column(Numeric())
    net_quantity_description = 'SIGNED net lots: positive = LONG, negative = SHORT.'
    net_quantity_application_rules = ['Never SUM net_quantity across topic history; compaction means history contains superseded snapshots.', 'Total open interest per series = SUM(ABS(net_quantity))/2 over the LATEST record per key only.']
    as_of_time = Column(DateTime)
    margin_initial = Column('margin.initial', Float, nullable=True)
    margin_initial_description = 'Lenses SQL path: margin.initial'
    margin_ccy = Column('margin.ccy', String)
    margin_ccy_description = 'Lenses SQL path: margin.ccy'

